name: Test PEM module
on:
  push:
    branches:
    - master
    - devel/*
    pull_request:
    - master
    paths:
    - .github/workflows/tests.yml
    - package.json
    - lib/**.js
    - bin/**.sh
    - test/**.js
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  TARGET: x86_64-unknown-linux-gnu
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x]
        OPENSSL_DIR: ['']
        LIBRARY: ['']
        VERSION: ['']
        include:
        - LIBRARY: openssl
          VERSION: 0.9.8zh
          OPENSSL_DIR: /openssl
        - LIBRARY: openssl
          VERSION: 1.0.1u
          OPENSSL_DIR: /openssl
        - LIBRARY: openssl
          VERSION: 1.0.2u
          OPENSSL_DIR: /openssl
        - LIBRARY: openssl
          VERSION: 1.1.0l
          OPENSSL_DIR: /openssl
        - LIBRARY: openssl
          VERSION: 1.1.1l
          OPENSSL_DIR: /openssl
        - LIBRARY: openssl
          VERSION: 3.0.1
          OPENSSL_DIR: /openssl
        - LIBRARY: libressl
          VERSION: 2.4.5
          OPENSSL_DIR: /openssl
        - LIBRARY: libressl
          VERSION: 2.5.5
          OPENSSL_DIR: /openssl
        - LIBRARY: libressl
          VERSION: 2.6.5
          OPENSSL_DIR: /openssl
        - LIBRARY: libressl
          VERSION: 2.7.5
          OPENSSL_DIR: /openssl
        - LIBRARY: libressl
          VERSION: 2.8.3
          OPENSSL_DIR: /openssl
        - LIBRARY: libressl
          VERSION: 2.9.2
          OPENSSL_DIR: /openssl
        - LIBRARY: libressl
          VERSION: 3.0.2
          OPENSSL_DIR: /openssl
        - LIBRARY: libressl
          VERSION: 3.1.5
          OPENSSL_DIR: /openssl
        - LIBRARY: libressl
          VERSION: 3.2.7
          OPENSSL_DIR: /openssl
        - LIBRARY: libressl
          VERSION: 3.3.5
          OPENSSL_DIR: /openssl
        - LIBRARY: libressl
          VERSION: 3.4.2
          OPENSSL_DIR: /openssl
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y haveged ca-certificates
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
    - run: |
        sudo haveged -w 2048
        mkdir openssl
    - name: Download OpenSSL Artifacts
      uses: actions/download-artifact@v3
      with:
        workflow: build_cache.yml
        name: openssl_build
        path: ./openssl/
    - name: Set ENV
      shell: bash
      run: |
        set -x
        ls -lah ./openssl
        tar xf ./openssl/all_versions.tar.xz --strip-components=1 -C ./openssl
        echo "LIBRARY=$(echo ${LIBRARY})" >> $GITHUB_ENV
        echo "VERSION=$(echo ${VERSION})" >> $GITHUB_ENV
      env:
        LIBRARY: ${{ matrix.LIBRARY }}
        VERSION: ${{ matrix.VERSION }}
    - name: Run Tests
      shell: bash
      run: |
        yarn install
        yarn run test
